### ISSUE TITLE
Some Icon characters not rendering in Windows

### ISSUE THREAD

**Issue by bfbiggs** [collab-ui/collab-ui-icons#7]
Windows only: When testing the component library in different environments noticed examples of certain characters that were used in content of a pseudo element not rendering. Behavior is consistent across all Windows browsers but not across all characters.

Browsers tested: Chrome, Safari, Edge, IE11.

<img width="610" alt="screen shot 2018-07-18 at 3 52 54 pm" src="https://user-images.githubusercontent.com/36969382/42908113-9e2239c8-8aa5-11e8-84af-a7b126010a5e.png">

**Comment by pauljeter** [comment]
Fixed in v3.16.0
