### ISSUE TITLE
Request for the following icons to support recording functionality in web client

### ISSUE THREAD

**Issue by saurjai3** [collab-ui/collab-ui-icons#9]
Request for the following icons to support recording functionality in web client:
1. icon-play-circle -> need size 20
2. icon-stop-circle -> need size 20
3. icon-pause-circle -> need size 20

**Comment by pauljeter** [comment]
Icons have been added to [@collab-ui/icons v3.23.0](https://github.com/collab-ui/collab-ui-icons/releases/tag/v3.23.0)
